# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    
  - main: ./cmd/cat
    id: "cli/cat/1"
    binary: cli-cat
    goos:
      - linux
  - main: ./cmd/echo
    id: "cli/echo/1"
    binary: cli-echo
    goos:
      - linux
  - main: ./cmd/env
    id: "cli/env/1"
    binary: cli-env
    goos:
      - linux
  - main: ./cmd/false
    id: "cli/false/1"
    binary: cli-false
    goos:
      - linux
  - main: ./cmd/head
    id: "cli/head/1"
    binary: cli-head
    goos:
      - linux
  - main: ./cmd/tail
    id: "cli/tail/1"
    binary: cli-tail
    goos:
      - linux
  - main: ./cmd/tree
    id: "cli/tree/1"
    binary: cli-tree
    goos:
      - linux
  - main: ./cmd/true
    id: "cli/true/1"
    binary: cli-true
    goos:
      - linux
  - main: ./cmd/wc
    id: "cli/wc/1"
    binary: cli-wc
    goos:
      - linux
  - main: ./cmd/yes
    id: "cli/yes/1"
    binary: cli-yes
    goos:
      - linux

archives:
  - format: binary
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
