name: coreutilsGo
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/checkout@v4
        with:
          go-version: '1.19.1'

      - name: Run Go-linter
        uses: golangci/golangci-lint-action@v3

      - name: Run build
        run: go build .